version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Fanlytics-URLShortener"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-164syzkk4pm51"
s3_prefix = "Fanlytics-URLShortener"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"fanlytics-url-shortener\" UseLocalClient=\"false\" GithubRepository=\"https://github.com/fanlytics/fanlytics-url-shortener\" CustomDomain=\"none\""
